### ISSUE TITLE
Python 用的是不是2.7版本的，我发现python3.6貌似不行

### ISSUE THREAD

**Issue by ithjz** [undersail/easybot#2]
没整出来， 兄弟建个qq群交流下吧
E:\ProgramData\Anaconda3\python.exe D:/360c/easybot-master/execute.py
Traceback (most recent call last):
  File "D:/360c/easybot-master/execute.py", line 18, in <module>
    import seq2seq_model
  File "D:\360c\easybot-master\seq2seq_model.py", line 28, in <module>
    from tensorflow.models.rnn.translate import data_utils
ModuleNotFoundError: No module named 'tensorflow.models'

Process finished with exit code 1

**Comment by undersail** [comment]
Python 和 TF 都是比较旧的版本
